service: pride-frame-backend

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: 'node18'
    platform: 'node'
    concurrency: 10

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:5173
        - https://dl1mzzuw9wm0m.cloudfront.net
      allowedMethods:
        - GET
        - POST
        - OPTIONS
      allowedHeaders:
        - Content-Type
  environment:
    BUCKET_NAME: pride-frame-images-${sls:stage}
    TABLE_NAME: PrideFrameGallery-${sls:stage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: arn:aws:s3:::pride-frame-images-${sls:stage}/*
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource:
        - arn:aws:dynamodb:ap-northeast-1:*:table/PrideFrameGallery-${sls:stage}

functions:
  generateUploadUrl:
    handler: functions/generateUploadUrl.handler
    events:
      - httpApi:
          path: /generate-upload-url
          method: post

  addGalleryItem:
    handler: functions/addGalleryItem.handler
    events:
      - httpApi:
          path: /add-gallery-item
          method: post

  listGalleryItems:
    handler: functions/listGalleryItems.handler
    events:
      - httpApi:
          path: /list-gallery-items
          method: get

  getGalleryItemById:
    handler: functions/getGalleryItemById.handler
    events:
      - httpApi:
          path: /get-gallery-item/{id}
          method: get

resources:
  Resources:
    PrideFrameGalleryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PrideFrameGallery-${sls:stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    PrideFrameImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: pride-frame-images-${sls:stage}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ['*']
              AllowedMethods: ['GET', 'PUT']
              AllowedOrigins: ['*']
              MaxAge: 3000
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false

    PrideFrameImagesBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref PrideFrameImagesBucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: '*'
              Action: s3:GetObject
              Resource: arn:aws:s3:::pride-frame-images-${sls:stage}/*
